name: Build Debian Package

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        runner: [ubuntu-latest, tr-linux-arm64]
    runs-on: ${{ matrix.runner }}

    steps:
    - uses: actions/checkout@v4
      with:
        path: /tmp/libtrossen_arm

    - name: Install dependencies
      run: sudo apt-get install -y build-essential

    - name: Build package
      run: |
        cd /tmp/libtrossen_arm
        make deb

    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        path: /tmp/libtrossen_arm/_packages/libtrossen_arm*.deb
